### ISSUE TITLE
CI/CD kernel packages

### ISSUE THREAD

**Issue by Kieran-Weaver** [macromorgan/chip-debroot#3]
Hi,
I got the kernel config working using `make olddefconfig` and the debian kernels 6.1 and 6.4. Would it be possible to build kernels for bullseye and bookworm using some kind of CI/CD pipeline? The generated deb files could be put in a repo accessible to apt.

**Comment by macromorgan** [comment]
Honestly for Bookworm I'm thinking of just adding a few drivers as DKMS and otherwise letting you use the included kernel otherwise. I haven't started building the image yet though, so it might be a little while.
